### ISSUE TITLE
While Searching Giving Random String that may mess things on my Project

### ISSUE THREAD

**Issue by MeetBhingradiya** [victrme/search-suggestions#4]
+ I Simple Searched `Meet `, Space Included

+ I am implemented this API to my own project `https://teamsm.vercel.app/Apps/NewTab`

![image](https://github.com/victrme/search-suggestions/assets/102130001/ff4d5226-327e-4da9-8d93-3a0a68d6a6aa)

+ From My Project with Bing

![image](https://github.com/victrme/search-suggestions/assets/102130001/087fafcf-0b91-42b9-ac78-0297dac07c77)

**Comment by victrme** [comment]
Hi @MeetBhingradiya, sorry for the wait.

Bing is using HTML for their suggestion API, which means I have to scrape the relevent data from their response. It appears that they changed how they handle thumbnails, and my scrapping broke...

If I have the time I'll try to find a way to get their API in a JSON format. For now I will patch this issue, but it will definitely break again 😢

**Comment by MeetBhingradiya** [comment]
@victrme as your wish i will try to manage, Thanks

**Comment by MeetBhingradiya** [comment]
@victrme I made a BookmarkSite i hope you chekout ones it using this api. also thanks for updating on json. #5 

Sitelink : https://meetbhingradiya.tech/Tools
